services:
  app:
    build: ./app
    ports:
      - "443:443"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads 
      - ./certs:/usr/src/app/certs
    environment:
      - DB_HOST=db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=network_db
      - DB_PORT=5432
      - JWT_SECRET=your_very_strong_secret_key_change_this 
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=network_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d network_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: